image: circleci/python:3.6.4-node

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

cache:
  paths:
    - .cache/pip
    - venv/
    - node_modules/

test:
  before_script:
    - python -V
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt -r testing-requirements.txt
    - if [ ! -d node_modules/sfdx-cli ]; then
          export SFDX_AUTOUPDATE_DISABLE=true;
          export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true;
          export SFDX_DOMAIN_RETRY=300;
          npm install sfdx-cli;
      fi;
  script:
    - sudo ln -s $(pwd)/node_modules/sfdx-cli/bin/run /usr/local/bin/sfdx;
    - sfdx --version
    - sfdx plugins --core
    - openssl aes-256-cbc -k $KEY -in assets/server.key.enc -out assets/server.key -d -md sha256
    - sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a DevHub
    - source assets/scripts/prep-scratch-org.sh
    - sfdx force:apex:execute -f assets/scripts/UpdateUser.apex -u scratch
    - pytest --junitxml=test-reports/junit.xml --cov-config pytest.ini --cov=amaxa
    - coveralls
  after_script:
    - sfdx force:org:delete -u scratch -p
    - rm assets/server.key
  artifacts:
    reports:
      junit: test-reports/junit.xml
  only: 
    - branches