stages:
  - test
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"

test_unit:
  image: python:3.6-slim
  stage: test
  cache:
    paths:
      - .cache/pip
      - venv/
  before_script:
    - python -V
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt -r testing-requirements.txt
  script:
    - pytest --junitxml=test-reports/junit.xml --cov-config pytest.ini --cov=amaxa amaxa/test
    - codecov
  artifacts:
    reports:
      junit: test-reports/junit.xml
  only: 
    - branches

test_org:
  image: circleci/python:3.6.4-node
  stage: test
  cache:
    paths:
      - .cache/pip
      - venv/
      - node_modules/
  before_script:
    - python -V
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt -r testing-requirements.txt
    - if [ ! -d node_modules/sfdx-cli ]; then
          export SFDX_AUTOUPDATE_DISABLE=true;
          export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true;
          export SFDX_DOMAIN_RETRY=300;
          npm install sfdx-cli;
      fi;
  script:
    - sudo ln -s $(pwd)/node_modules/sfdx-cli/bin/run /usr/local/bin/sfdx;
    - sfdx --version
    - openssl aes-256-cbc -k $KEY -in assets/server.key.enc -out assets/server.key -d -md sha256
    - sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key --username $USERNAME --setdefaultdevhubusername -a DevHub
    - source assets/scripts/prep-scratch-org.sh
    - pytest --junitxml=test-reports/junit.xml --cov-config pytest.ini --cov=amaxa amaxa/test_org
    - codecov
  after_script:
    - sfdx force:org:delete -u scratch -p
    - rm assets/server.key
  artifacts:
    reports:
      junit: test-reports/junit.xml
  only:
    - branches

build_package:
  image: python:3.6-slim
  stage: build
  cache:
    paths:
      - .cache/pip
      - venv/
  before_script:
    - python -V
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python setup.py bdist_wheel
  only:
    - branches
  artifacts:
    paths:
      dist/*.whl

upload_package:
  stage: deploy
  when: manual
  image: python:3.6-slim
  variables:
    TWINE_USERNAME: $PYPI_PRODUCTION_USERNAME
    TWINE_PASSWORD: $PYPI_PRODUCTION_PASSWORD
  before_script:
    - python -V
    - python -m venv venv
    - source venv/bin/activate
    - pip install --upgrade pip
    - pip install -r requirements.txt twine
  script:
    - python setup.py bdist_wheel
    - twine upload dist/*
  only:
    - tags