name: Integration Test

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  integration-test:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python
          uses: actions/setup-python@v1
          with:
            python-version: ${{ matrix.python }}
        - uses: actions/cache@v1
          with:
            path: ~/.cache/pip
            key: ${{ runner.os }}-pip-${{ hashFiles('**/poetry.lock') }}
            restore-keys: |
              ${{ runner.os }}-pip-
        - name: Install SFDX
          shell: bash
          run: |
              wget https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
              mkdir sfdx-cli
              tar xJf sfdx-linux-amd64.tar.xz -C sfdx-cli --strip-components 1
              ./sfdx-cli/install
        - name: Create Scratch Org
          shell: bash
          run: |
              echo ${{ secrets.DEVHUB_SFDX_URL}} > ./DEVHUB_SFDX_URL.txt
              sfdx force:auth:sfdxurl:store -f ./DEVHUB_SFDX_URL.txt -a DevHub -d
              source assets/scripts/prep-scratch-org.sh
        - name: Run Tests
          shell: bash
          run: |
              source assets/scripts/get-auth-params.sh
              tox test/test_org
              codecov -F integration
        - name: Delete Scratch Org
          if: always()
          run: 'sfdx force:org:delete -p -u amaxa'
